//
// "Open in Spud" Safari content script.
//
// Runs only on hosts in the bundled instance allowlist (see manifest `matches`,
// generated by scripts/generate-safari-matches.swift). On a recognized Lemmy
// content page it shows a dismissible banner; tapping it hands the page URL to
// the app via the `resolve` deep link, which the app resolves and routes.
//
// No auto-redirect: reading in Safari is never hijacked. The pure helpers are
// exported for the node test; the DOM code is guarded so importing this file
// outside a browser is side-effect free.

"use strict";

// Recognized Lemmy content paths: /post/<id>, /comment/<id>, /c/<name>, /u/<name>.
function isLemmyContentPath(pathname) {
    return /^\/(post|comment|c|u)\/[^/]+/.test(pathname);
}

// Wraps a page URL in the app's resolve deep link. The app decodes the `url`
// query item and resolves it via Lemmy resolve_object.
function lemmyDeepLink(href) {
    return "info.ddenis.spud://internal/resolve?url=" + encodeURIComponent(href);
}

// Maps a message from the toolbar popup to a response, performing the
// navigation for an "open" request. Pure except for the injected `deps`:
//   deps.getHref()      -> the current page URL
//   deps.navigate(url)  -> perform the navigation (page -> deep link)
// Returns the object to send back to the popup, or undefined for a message
// this listener does not handle. Reuses lemmyDeepLink so the popup and the
// in-page banner share one deep-link form.
function handlePopupMessage(message, deps) {
    if (!message || typeof message.type !== "string") {
        return undefined;
    }
    if (message.type === "spud-probe") {
        // The content script only runs on allowlisted Lemmy hosts, so a reply
        // at all is the "known instance" signal the popup is looking for.
        return { known: true };
    }
    if (message.type === "spud-open") {
        deps.navigate(lemmyDeepLink(deps.getHref()));
        return { ok: true };
    }
    return undefined;
}

// Localized string with an English fallback when i18n is unavailable.
function localized(key, fallback) {
    try {
        const message = globalThis.browser && globalThis.browser.i18n
            ? globalThis.browser.i18n.getMessage(key)
            : "";
        return message || fallback;
    } catch (e) {
        return fallback;
    }
}

const BANNER_ID = "spud-open-in-spud-banner";

function dismissKey() {
    return "spud-open-in-spud-dismissed:" + window.location.pathname;
}

function showBanner() {
    if (document.getElementById(BANNER_ID)) {
        return;
    }
    try {
        if (window.sessionStorage.getItem(dismissKey()) === "1") {
            return;
        }
    } catch (e) {
        // sessionStorage can throw in private mode; just show the banner.
    }

    const banner = document.createElement("div");
    banner.id = BANNER_ID;
    banner.style.cssText = [
        "position:fixed",
        "left:0",
        "right:0",
        "bottom:0",
        "z-index:2147483647",
        "display:flex",
        "align-items:center",
        "gap:12px",
        "padding:12px 16px",
        "background:#1c1c1e",
        "color:#fff",
        "font:600 15px -apple-system,system-ui,sans-serif",
        "box-shadow:0 -2px 12px rgba(0,0,0,0.35)",
    ].join(";");

    const label = document.createElement("span");
    label.textContent = localized("banner_title", "Open this in Spud?");
    label.style.cssText = "flex:1";

    const openButton = document.createElement("button");
    openButton.textContent = localized("banner_open", "Open");
    openButton.style.cssText = [
        "border:0",
        "border-radius:8px",
        "padding:8px 16px",
        "background:#30b0c7",
        "color:#fff",
        "font:inherit",
        "cursor:pointer",
    ].join(";");
    openButton.addEventListener("click", function () {
        window.location.href = lemmyDeepLink(window.location.href);
    });

    const dismissButton = document.createElement("button");
    dismissButton.setAttribute("aria-label", localized("banner_dismiss", "Dismiss"));
    dismissButton.textContent = "✕";
    dismissButton.style.cssText = [
        "border:0",
        "background:transparent",
        "color:#aaa",
        "font:inherit",
        "font-size:18px",
        "cursor:pointer",
    ].join(";");
    dismissButton.addEventListener("click", function () {
        try {
            window.sessionStorage.setItem(dismissKey(), "1");
        } catch (e) {
            // ignore storage failures
        }
        banner.remove();
    });

    banner.appendChild(label);
    banner.appendChild(openButton);
    banner.appendChild(dismissButton);
    document.body.appendChild(banner);
}

// Browser-only entry point. Guarded so importing this file in node (for the
// helper tests) has no side effects.
if (typeof window !== "undefined" && typeof document !== "undefined") {
    if (isLemmyContentPath(window.location.pathname)) {
        if (document.body) {
            showBanner();
        } else {
            document.addEventListener("DOMContentLoaded", showBanner);
        }
    }
    if (typeof browser !== "undefined" && browser.runtime && browser.runtime.onMessage) {
        browser.runtime.onMessage.addListener(function (message) {
            const response = handlePopupMessage(message, {
                getHref: function () { return window.location.href; },
                navigate: function (url) { window.location.href = url; },
            });
            // Returning a Promise sends the response; false means "not handled"
            // so other listeners (and the sender's catch) behave correctly.
            return response === undefined ? false : Promise.resolve(response);
        });
    }
}

if (typeof module !== "undefined" && module.exports) {
    module.exports = { isLemmyContentPath, lemmyDeepLink, handlePopupMessage };
}
