#!/bin/sh

if [ -n "$(git diff --name-only --cached | grep 'project.pbxproj')" ]; then
  echo "Sorting Xcode project file..."
  perl scripts/sort-Xcode-project-file.pl Spud.xcodeproj/project.pbxproj
  git add Spud.xcodeproj/project.pbxproj
fi

mint run swiftformat --lint .

exit 0
