//
// Copyright (c) 2026, Denis Dzyubenko <denis@ddenis.info>
//
// SPDX-License-Identifier: BSD-2-Clause
//

import Foundation

/// Anchors `Bundle(for:)` to the SpudDataKit framework bundle that carries the
/// compressed seed resources.
final class ExplorerSeedBundleToken { }

/// Loads the bundled, LZFSE-compressed Lemmy Explorer seed shipped with the app
/// (generated by `scripts/generate-explorer-seed.swift`). The seed gives the
/// app the full directory on first launch with no network. See ``ExplorerService``
/// for how it is imported, and the runtime refresh that supersedes it.
enum ExplorerSeed {
    private static var bundle: Bundle {
        Bundle(for: ExplorerSeedBundleToken.self)
    }

    /// Decoded seed payload: the records plus the timestamp the seed was built,
    /// which seeds `lastFetchedAt` so a sufficiently old seed triggers a refresh.
    struct Payload<Element: Decodable & Sendable>: Decodable {
        let generatedAt: Date
        let records: [Element]
    }

    static func loadInstances() throws -> Payload<ExplorerInstanceDTO>? {
        try load(resource: "explorer-instance.seed.json")
    }

    static func loadCommunities() throws -> Payload<ExplorerCommunityDTO>? {
        try load(resource: "explorer-community.seed.json")
    }

    private static func load<Element: Decodable & Sendable>(
        resource: String
    ) throws -> Payload<Element>? {
        guard let url = bundle.url(forResource: resource, withExtension: "lzfse") else {
            return nil
        }
        let compressed = try Data(contentsOf: url)
        let json = try (compressed as NSData).decompressed(using: .lzfse) as Data
        let decoder = JSONDecoder()
        decoder.dateDecodingStrategy = .secondsSince1970
        return try decoder.decode(Payload<Element>.self, from: json)
    }
}
